### ISSUE TITLE
Improvement command "common"

### ISSUE THREAD

**Issue by ms-gx** [shenwei356/unikmer#17]
I would much appreciate it if you add a flag `-n` to command `common` which specifies minimum number of files which have to share a kmer. Additional to `-p`.

**Comment by shenwei356** [comment]
added 

- [unikmer_darwin_amd64.tar.gz](https://github.com/shenwei356/unikmer/files/5352734/unikmer_darwin_amd64.tar.gz)
- [unikmer_linux_amd64.tar.gz](https://github.com/shenwei356/unikmer/files/5352735/unikmer_linux_amd64.tar.gz)

**Comment by ms-gx** [comment]
Thanks much!
