### ISSUE TITLE
dependency issue with nthash

### ISSUE THREAD

**Issue by cmdoret** [shenwei356/unikmer#18]
Hello,

First, hank you for all the great go packages you develop, it really helped me getting started with golang in comp. bio :)

I just wanted to report what I believe to be an inconsistency in unikmer dependencies. I imported unikmer in my go code and it works great, however when trying to setup go mod in my package, I get a dependency error:

```
        github.com/shenwei356/unikmer imports
        github.com/shenwei356/nthash: github.com/shenwei356/nthash@v0.2.0: parsing go.mod:
        module declares its path as: github.com/will-rowe/nthash
                but was required as: github.com/shenwei356/nthash
```

It seems unikmer imports your fork of nthash, but your nthash fork's go mod file has the upstream module url instead of its own: https://github.com/shenwei356/nthash/blob/master/go.mod.

**Comment by shenwei356** [comment]
Hey, I'm sorry, I missed this issue. I've changed the import path.

Yes you're right, I forked nthash and added some features at that time, and they were soon merged to upstream. But I forgot changing the path.

I never use go mod :(
