### ISSUE TITLE
Fails to build on 32-bit architectures

### ISSUE THREAD

**Issue by nileshpatra** [shenwei356/unikmer#21]
Hi,
Thanks a lot for your work on unikmer.

At the moment, it works great for 64 bit architectures, but seems to fail on 32-bit ones -- reason  being `1<<32 - 1` directly being used [here](https://github.com/shenwei356/unikmer/blob/master/sketch.go#L94) which results in a: `src/github.com/shenwei356/unikmer/sketch.go:94:16: constant 4294967295 overflows int`

Could you please fix this with compatible type for 32-bit arches?

CC: @shenwei356

**Comment by shenwei356** [comment]
fixed
