### ISSUE TITLE
Request for more instructions in README.md on hashes

### ISSUE THREAD

**Issue by jelber2** [shenwei356/unikmer#23]
Hi,

Very cool tool, and in go-lang! I would suggest adding some instructions on how to use hash-based "mer" operations. For example when specifying minimizers, syncmers, or k>32 (I think), one needs to provide the reference (or original FASTA/FASTQ sequence) after the `unikmer count` step for `unikmer view` to view original sequence with the `-g original.fasta.gz` flag. With at least cf2a224, this is only clear when playing around with the `unikmer view --help` and/or trial and error.

**Comment by shenwei356** [comment]
Sorry for the late reply, I missed this issue.

The minimizer/syncmers part mainly acts as a library for another project, which I'll make public soon. 

In the `unikmer` tool, the usefulness of minimizer/syncmers are limited right now, but I'll continue to explore them soon after I finished the other project. And more documents will be available.

**Comment by shenwei356** [comment]
> For example when specifying minimizers, syncmers, or k>32 (I think), one needs to provide the reference (or original FASTA/FASTQ sequence) after the unikmer count step for unikmer view to view original sequence with the -g original.fasta.gz flag.

I've also added a little example.

**Comment by shenwei356** [comment]
also released a new version. https://github.com/shenwei356/unikmer/releases/tag/v0.18.7

**Comment by jelber2** [comment]
Cool! Thank you!
