### ISSUE TITLE
Make new release?

### ISSUE THREAD

**Issue by tseemann** [shenwei356/unikmer#7]
lots of new changes

unikmer v0.6.2
@shenwei356 shenwei356 released this on 21 Jan · 42 commits to master since this release

a new tag would be fine: `git tag v0.6.3 && git push --tags`

**Comment by shenwei356** [comment]
sure

**Comment by shenwei356** [comment]
BTW, are you using this tool?

**Comment by tseemann** [comment]
Was going to package it first, then look at it.
